---
apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: set kubeconfig
description: set a kubeconfig from a encrypted secret
inputs:
  kubeconfig:
    description: A reference to your kubeconfig as a secret
    required: true
runs:
  using: composite
  steps:
    - id: createconfig
      name: create kube config
      uses: docker://bitnami/kubectl:latest
      shell: sh
      run: |
          
          mkdir -p $HOME/.kube
          printf ${{ inputs.kubeconfig }} |base64 --decode >.kube/config
          printf "kubeconfig set\n"
